# 파일 입출력 및 데이터 필터링

1. CSV, JSON, Excel 파일 읽고 저장하기 
2. head(), shape, info(), describe()로 데이터 기본 정보 확인 
3. 조건식을 사용하여 필요한 데이터 필터링 
4. sort_values()로 데이터 정렬
5. groupby()로 라인별, 설비별, 상태별 요약표 작성

In [1]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [2]:
# 기본 라이브러리 읽어 오기

import numpy as np
import pandas as pd
from datetime import datetime, timedelta

In [4]:
# CSV 파일 읽기 

file_path = r"C:\Users\user\Desktop\python_campus\dev\data\raw\week07_day03_sensor_data.csv"

df_csv = pd.read_csv(file_path, encoding="utf-8-sig") # csv에서는 utf-8-sig 로 함 

df_csv

,timestamp,line,machine_id,product,temperature,pressure,speed,humidity,vibration,current,quality_score,status
0,2026-07-01 09:00:00,Line_C,EQP_04,P_A,27.56,2.593,6.44,65.01,0.293,8.64,92.5,OK
1,2026-07-01 09:01:00,Line_A,EQP_01,P_C,23.86,2.660,6.23,53.22,0.295,7.43,94.2,OK
2,2026-07-01 09:02:00,Line_C,EQP_03,P_A,23.32,2.987,4.83,63.18,0.347,8.80,92.1,OK
3,2026-07-01 09:03:00,Line_C,EQP_04,P_B,27.21,2.953,5.68,68.65,0.296,8.99,92.3,OK
4,2026-07-01 09:04:00,Line_A,EQP_04,P_B,25.44,2.795,5.45,45.17,0.279,8.95,94.7,OK
...,...,...,...,...,...,...,...,...,...,...,...,...
115,2026-07-01 10:55:00,Line_B,EQP_03,P_A,24.27,2.613,5.03,60.36,0.193,9.02,95.3,OK
116,2026-07-01 10:56:00,Line_A,EQP_01,P_B,28.25,3.188,4.40,60.08,0.277,8.37,90.4,OK
117,2026-07-01 10:57:00,Line_C,EQP_01,P_A,26.77,2.829,4.73,59.86,0.325,8.62,92.2,OK
118,2026-07-01 10:58:00,Line_C,EQP_01,P_C,28.03,3.095,5.70,61.19,0.343,9.47,90.0,OK
119,2026-07-01 10:59:00,Line_B,EQP_04,P_A,27.57,2.817,4.60,59.13,0.412,7.85,90.5,OK

In [5]:
df_csv.head()

,timestamp,line,machine_id,product,temperature,pressure,speed,humidity,vibration,current,quality_score,status
0,2026-07-01 09:00:00,Line_C,EQP_04,P_A,27.56,2.593,6.44,65.01,0.293,8.64,92.5,OK
1,2026-07-01 09:01:00,Line_A,EQP_01,P_C,23.86,2.660,6.23,53.22,0.295,7.43,94.2,OK
2,2026-07-01 09:02:00,Line_C,EQP_03,P_A,23.32,2.987,4.83,63.18,0.347,8.80,92.1,OK
3,2026-07-01 09:03:00,Line_C,EQP_04,P_B,27.21,2.953,5.68,68.65,0.296,8.99,92.3,OK
4,2026-07-01 09:04:00,Line_A,EQP_04,P_B,25.44,2.795,5.45,45.17,0.279,8.95,94.7,OK

In [6]:
df_csv.head(10)

,timestamp,line,machine_id,product,temperature,pressure,speed,humidity,vibration,current,quality_score,status
0,2026-07-01 09:00:00,Line_C,EQP_04,P_A,27.56,2.593,6.44,65.01,0.293,8.64,92.5,OK
1,2026-07-01 09:01:00,Line_A,EQP_01,P_C,23.86,2.660,6.23,53.22,0.295,7.43,94.2,OK
2,2026-07-01 09:02:00,Line_C,EQP_03,P_A,23.32,2.987,4.83,63.18,0.347,8.80,92.1,OK
3,2026-07-01 09:03:00,Line_C,EQP_04,P_B,27.21,2.953,5.68,68.65,0.296,8.99,92.3,OK
4,2026-07-01 09:04:00,Line_A,EQP_04,P_B,25.44,2.795,5.45,45.17,0.279,8.95,94.7,OK
5,2026-07-01 09:05:00,Line_A,EQP_02,P_B,27.79,2.829,5.96,55.22,0.361,9.36,90.3,OK
6,2026-07-01 09:06:00,Line_C,EQP_03,P_C,27.18,3.119,4.32,63.46,0.325,9.17,89.7,OK
7,2026-07-01 09:07:00,Line_B,EQP_03,P_A,25.82,2.652,5.48,58.78,0.500,8.87,91.7,OK
8,2026-07-01 09:08:00,Line_C,EQP_01,P_A,23.88,2.937,5.74,62.23,0.085,8.44,97.0,OK
9,2026-07-01 09:09:00,Line_C,EQP_03,P_A,22.21,2.749,3.77,56.38,0.459,7.17,86.2,NG

In [7]:
df_csv.tail(10)

,timestamp,line,machine_id,product,temperature,pressure,speed,humidity,vibration,current,quality_score,status
110,2026-07-01 10:50:00,Line_C,EQP_04,P_C,25.48,2.978,5.45,71.09,0.421,9.16,92.6,OK
111,2026-07-01 10:51:00,Line_B,EQP_04,P_B,24.77,2.519,3.84,66.76,0.294,8.91,91.4,OK
112,2026-07-01 10:52:00,Line_A,EQP_02,P_C,24.53,2.416,4.95,58.39,0.413,9.35,92.3,OK
113,2026-07-01 10:53:00,Line_C,EQP_03,P_C,28.12,3.119,4.15,53.36,0.447,9.44,86.2,NG
114,2026-07-01 10:54:00,Line_A,EQP_02,P_B,26.89,2.883,4.54,75.44,0.412,9.61,89.0,OK
115,2026-07-01 10:55:00,Line_B,EQP_03,P_A,24.27,2.613,5.03,60.36,0.193,9.02,95.3,OK
116,2026-07-01 10:56:00,Line_A,EQP_01,P_B,28.25,3.188,4.40,60.08,0.277,8.37,90.4,OK
117,2026-07-01 10:57:00,Line_C,EQP_01,P_A,26.77,2.829,4.73,59.86,0.325,8.62,92.2,OK
118,2026-07-01 10:58:00,Line_C,EQP_01,P_C,28.03,3.095,5.70,61.19,0.343,9.47,90.0,OK
119,2026-07-01 10:59:00,Line_B,EQP_04,P_A,27.57,2.817,4.60,59.13,0.412,7.85,90.5,OK

In [9]:
# 엑셀 파일 읽어 오기
file_path = r"C:\Users\user\Desktop\python_campus\dev\data\raw\week07_day03_sensor_data.xlsx"

df_excel = pd.read_excel(file_path)

df_excel.head()

,timestamp,line,machine_id,product,temperature,pressure,speed,humidity,vibration,current,quality_score,status
0,2026-07-01 09:00:00,Line_C,EQP_04,P_A,27.56,2.593,6.44,65.01,0.293,8.64,92.5,OK
1,2026-07-01 09:01:00,Line_A,EQP_01,P_C,23.86,2.660,6.23,53.22,0.295,7.43,94.2,OK
2,2026-07-01 09:02:00,Line_C,EQP_03,P_A,23.32,2.987,4.83,63.18,0.347,8.80,92.1,OK
3,2026-07-01 09:03:00,Line_C,EQP_04,P_B,27.21,2.953,5.68,68.65,0.296,8.99,92.3,OK
4,2026-07-01 09:04:00,Line_A,EQP_04,P_B,25.44,2.795,5.45,45.17,0.279,8.95,94.7,OK

In [ ]:
# json 파일 읽어 오기
file_path = r"C:\Users\user\Desktop\python_campus\dev\data\raw\week07_day03_sensor_data.json"

df_json = pd.read_json(file_path)

df_json.head()

,timestamp,line,machine_id,product,temperature,pressure,speed,humidity,vibration,current,quality_score,status
0,2026-07-01 09:00:00,Line_C,EQP_04,P_A,27.56,2.593,6.44,65.01,0.293,8.64,92.5,OK
1,2026-07-01 09:01:00,Line_A,EQP_01,P_C,23.86,2.660,6.23,53.22,0.295,7.43,94.2,OK
2,2026-07-01 09:02:00,Line_C,EQP_03,P_A,23.32,2.987,4.83,63.18,0.347,8.80,92.1,OK
3,2026-07-01 09:03:00,Line_C,EQP_04,P_B,27.21,2.953,5.68,68.65,0.296,8.99,92.3,OK
4,2026-07-01 09:04:00,Line_A,EQP_04,P_B,25.44,2.795,5.45,45.17,0.279,8.95,94.7,OK

In [ ]:
df_json.shape  # 행과 열 구조 확인

(120, 12)

In [12]:
df_json.columns # 컬럼명 확인

Index(['timestamp', 'line', 'machine_id', 'product', 'temperature', 'pressure',
       'speed', 'humidity', 'vibration', 'current', 'quality_score', 'status'],
      dtype='str')

In [13]:
df_json.info() # 데이터 타입과 결측치 확인

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      120 non-null    datetime64[ms]
 1   line           120 non-null    str
 2   machine_id     120 non-null    str
 3   product        120 non-null    str
 4   temperature    120 non-null    float64
 5   pressure       120 non-null    float64
 6   speed          120 non-null    float64
 7   humidity       120 non-null    float64
 8   vibration      120 non-null    float64
 9   current        120 non-null    float64
 10  quality_score  120 non-null    float64
 11  status         120 non-null    str
dtypes: datetime64[ms](1), float64(7), str(4)
memory usage: 11.4 KB

In [14]:
df_json.describe() # 데이터의 평균, 표준편차, 최소값, 최대값 (통계량 확인)

,timestamp,temperature,pressure,speed,humidity,vibration,current,quality_score
count,120,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,2026-07-01 09:59:30,26.048417,2.820717,4.904750,60.291667,0.345492,8.662000,91.010000
min,2026-07-01 09:00:00,17.900000,2.269000,3.390000,43.820000,0.085000,7.170000,80.000000
25%,2026-07-01 09:29:45,24.260000,2.655000,4.385000,57.115000,0.278500,8.090000,89.150000
50%,2026-07-01 09:59:30,26.185000,2.814500,4.890000,60.345000,0.345000,8.650000,91.350000
75%,2026-07-01 10:29:15,27.637500,2.960250,5.400000,64.222500,0.412250,9.180000,93.000000
max,2026-07-01 10:59:00,35.630000,3.347000,7.160000,75.440000,0.613000,10.520000,97.000000
std,NaN,2.591504,0.220868,0.721419,6.227116,0.100540,0.731442,2.908099

In [15]:
# 결측치 = 데이터가 있어야 하는데 비어 있는 값

In [16]:
# 필요한 컬럼만 선택하기

df_json["temperature"].tail()

115    24.27
116    28.25
117    26.77
118    28.03
119    27.57
Name: temperature, dtype: float64

In [17]:
# 여러 개의 컬럼을 선택해서 보기

selected_columns = ["timestamp", "line", "machine_id", "temperature", "pressure", "status"]

df_json[selected_columns].head()

            timestamp    line machine_id  temperature  pressure status
0 2026-07-01 09:00:00  Line_C     EQP_04        27.56     2.593     OK
1 2026-07-01 09:01:00  Line_A     EQP_01        23.86     2.660     OK
2 2026-07-01 09:02:00  Line_C     EQP_03        23.32     2.987     OK
3 2026-07-01 09:03:00  Line_C     EQP_04        27.21     2.953     OK
4 2026-07-01 09:04:00  Line_A     EQP_04        25.44     2.795     OK

In [22]:
# 조건으로 데이터 필터링 하기 

# 온도가 30도 이상인 데이터만 필터링 하기 

high_temp = df_json[df_json["temperature"] >= 30]

high_temp["temperature"]
# len(high_temp["temperature"])

29     35.63
40     31.79
54     31.36
68     30.41
72     31.31
86     30.08
104    31.33
Name: temperature, dtype: float64

In [ ]:
high_temp["temperature"].describe() # high temp의 온도 통계 보기

count     7.000000
mean     31.701429
std       1.832398
min      30.080000
25%      30.860000
50%      31.330000
75%      31.575000
max      35.630000
Name: temperature, dtype: float64

In [24]:
df_json["status"]

0      OK
1      OK
2      OK
3      OK
4      OK
       ..
115    OK
116    OK
117    OK
118    OK
119    OK
Name: status, Length: 120, dtype: str

In [26]:
# status가 NG인 데이터만 필터링 하기 (품질 문제 데이터 확인할 때 자주 사용)

ng_data = df_json[df_json["status"] == "NG"]

ng_data["status"].head()

9     NG
11    NG
17    NG
22    NG
23    NG
Name: status, dtype: str

In [ ]:
df_json["status"].unique() # 컬럼내 유니크(유일)한 요소를 확인

<StringArray>
['OK', 'NG']
Length: 2, dtype: str

In [30]:
df_json.columns

Index(['timestamp', 'line', 'machine_id', 'product', 'temperature', 'pressure',
       'speed', 'humidity', 'vibration', 'current', 'quality_score', 'status'],
      dtype='str')

In [31]:
df_json["line"].unique()

<StringArray>
['Line_C', 'Line_A', 'Line_B']
Length: 3, dtype: str

In [32]:
df_json["machine_id"].unique()

<StringArray>
['EQP_04', 'EQP_01', 'EQP_03', 'EQP_02']
Length: 4, dtype: str

In [33]:
# 여러 조건을 동시에 사용하여 필터링을 진행
# pandas에서 and 조건은 &, or 조건은 | 사용
# 조건을 여러개 사용시 괄호를 넣어야 함 

line_a_ng = df_json[(df_json["line"]=="Line_A") & (df_json["status"]=="NG")]  # Line A와 NG 조건을 필터링 

line_a_ng.head()

,timestamp,line,machine_id,product,temperature,pressure,speed,humidity,vibration,current,quality_score,status
40,2026-07-01 09:40:00,Line_A,EQP_03,P_C,31.79,2.594,6.38,62.03,0.298,8.09,88.1,NG
51,2026-07-01 09:51:00,Line_A,EQP_03,P_C,26.54,3.169,3.39,57.13,0.340,7.77,88.9,NG
87,2026-07-01 10:27:00,Line_A,EQP_02,P_B,22.42,3.269,4.40,59.25,0.274,8.77,90.7,NG
95,2026-07-01 10:35:00,Line_A,EQP_02,P_A,27.16,2.683,5.53,50.07,0.613,9.94,87.1,NG

In [34]:
# between()으로 특정 범위에 들어오는 데이터를 필터링 
# 압력이 2.7 이상 3.0 이하인 데이터를 필터링 하기 

normal_pressure_range = df_json[df_json["pressure"].between(2.7, 3.0)]

normal_pressure_range.head()

,timestamp,line,machine_id,product,temperature,pressure,speed,humidity,vibration,current,quality_score,status
2,2026-07-01 09:02:00,Line_C,EQP_03,P_A,23.32,2.987,4.83,63.18,0.347,8.80,92.1,OK
3,2026-07-01 09:03:00,Line_C,EQP_04,P_B,27.21,2.953,5.68,68.65,0.296,8.99,92.3,OK
4,2026-07-01 09:04:00,Line_A,EQP_04,P_B,25.44,2.795,5.45,45.17,0.279,8.95,94.7,OK
5,2026-07-01 09:05:00,Line_A,EQP_02,P_B,27.79,2.829,5.96,55.22,0.361,9.36,90.3,OK
8,2026-07-01 09:08:00,Line_C,EQP_01,P_A,23.88,2.937,5.74,62.23,0.085,8.44,97.0,OK

In [35]:
normal_pressure_range["pressure"].describe()

count    57.000000
mean      2.848105
std       0.079458
min       2.700000
25%       2.795000
50%       2.830000
75%       2.923000
max       2.998000
Name: pressure, dtype: float64

In [37]:
# 데이터 정렬하기 

# quality_score (품질 점수)가 낮은 데이터부터 정렬하기 

low_quality_score = df_json.sort_values(by="quality_score", ascending=True) # ascending은 올림차순 정렬 

low_quality_score.head(10)

,timestamp,line,machine_id,product,temperature,pressure,speed,humidity,vibration,current,quality_score,status
29,2026-07-01 09:29:00,Line_C,EQP_03,P_A,35.63,2.957,4.26,57.89,0.394,7.78,80.0,NG
82,2026-07-01 10:22:00,Line_B,EQP_04,P_A,17.90,2.269,4.02,71.29,0.288,9.74,82.5,NG
104,2026-07-01 10:44:00,Line_C,EQP_01,P_B,31.33,2.687,4.47,58.53,0.465,9.05,83.7,NG
102,2026-07-01 10:42:00,Line_C,EQP_04,P_B,29.97,2.801,4.54,58.44,0.606,8.11,85.2,NG
105,2026-07-01 10:45:00,Line_C,EQP_04,P_B,21.12,2.956,3.74,58.36,0.280,9.98,85.2,NG
9,2026-07-01 09:09:00,Line_C,EQP_03,P_A,22.21,2.749,3.77,56.38,0.459,7.17,86.2,NG
113,2026-07-01 10:53:00,Line_C,EQP_03,P_C,28.12,3.119,4.15,53.36,0.447,9.44,86.2,NG
79,2026-07-01 10:19:00,Line_B,EQP_03,P_B,27.94,2.598,4.03,61.34,0.451,9.01,86.6,NG
22,2026-07-01 09:22:00,Line_B,EQP_01,P_B,28.71,2.595,3.55,65.23,0.298,8.58,86.8,NG
95,2026-07-01 10:35:00,Line_A,EQP_02,P_A,27.16,2.683,5.53,50.07,0.613,9.94,87.1,NG

In [41]:
# 여러 기준으로 정렬하기 
# line 기준으로 정렬하고, 같은 line 안에서는 timestamp 기준으로 정렬 

line_time_sorted = df_json.sort_values(by=["line", "machine_id"], ascending=[True, True])
line_time_sorted.head(10)

,timestamp,line,machine_id,product,temperature,pressure,speed,humidity,vibration,current,quality_score,status
1,2026-07-01 09:01:00,Line_A,EQP_01,P_C,23.86,2.660,6.23,53.22,0.295,7.43,94.2,OK
15,2026-07-01 09:15:00,Line_A,EQP_01,P_B,26.96,2.805,5.05,57.53,0.272,9.34,92.4,OK
47,2026-07-01 09:47:00,Line_A,EQP_01,P_C,23.31,2.448,5.53,54.90,0.525,8.08,91.6,OK
81,2026-07-01 10:21:00,Line_A,EQP_01,P_C,25.85,2.650,6.34,62.83,0.222,7.29,95.3,OK
83,2026-07-01 10:23:00,Line_A,EQP_01,P_A,23.44,2.669,5.39,68.07,0.353,9.94,91.0,OK
84,2026-07-01 10:24:00,Line_A,EQP_01,P_B,25.37,2.610,4.54,69.56,0.402,8.01,93.3,OK
90,2026-07-01 10:30:00,Line_A,EQP_01,P_A,29.60,2.575,5.19,49.85,0.258,8.36,90.8,OK
92,2026-07-01 10:32:00,Line_A,EQP_01,P_A,28.91,2.470,4.83,59.05,0.252,7.40,90.9,OK
106,2026-07-01 10:46:00,Line_A,EQP_01,P_B,25.62,2.533,3.86,43.82,0.347,8.97,90.2,OK
108,2026-07-01 10:48:00,Line_A,EQP_01,P_B,26.70,2.830,5.18,58.61,0.287,8.97,93.1,OK

In [49]:
# groupby 로 요약하기 

# line별 데이터 개수와 평균 센서값을 요약하기 

line_summary = df_json.groupby("line").agg(
    # 수집하는 정보를 입력
    data_count = ("timestamp", "count"),  # 대상 컬럼, 평균/개수/최대/최소
    avg_temperature = ("temperature", "mean"),
    avg_pressure = ("pressure", "mean"),
    avg_speed = ("speed", "mean"),
    avg_quality_score = ("quality_score", "mean"),
).reset_index()

line_summary

,line,data_count,avg_temperature,avg_pressure,avg_speed,avg_quality_score
0,Line_A,39,25.713333,2.775974,5.081026,92.238462
1,Line_B,40,26.157750,2.825225,4.793500,90.795000
2,Line_C,41,26.260488,2.858878,4.845610,90.051220

In [50]:
# 설비별 OK/NG 개수를 계산하기 

machine_status_summary = df_json.groupby(["machine_id", "status"]).agg(
    count = ("timestamp", "count")
).reset_index()

machine_status_summary

  machine_id status  count
0     EQP_01     NG      5
1     EQP_01     OK     27
2     EQP_02     NG      4
3     EQP_02     OK     21
4     EQP_03     NG     13
5     EQP_03     OK     21
6     EQP_04     NG      4
7     EQP_04     OK     25

In [ ]:
# pivot_table을 사용하면 설비별 OK/NG 개수를 표 형태로 보기 좋게 만들 수 있음 

machine_status_pivot = pd.pivot_table(
    df_json,    # 대상 데이터프레임 지정 
    index = "machine_id", # 인덱스 컬럼 
    columns = "product", # 컬럼 (OK, NG 가 나뉘어 컬럼으로 들어가게 됨)
    values = "pressure", # 실제 피봇에서 사용할 데이터 
    aggfunc = "mean", # 수집할 함수 (개수, 평균/최대/최소/표준편차)
    fill_value = 0, # 결측치는 0으로 채우겠다는 것 (기본 값 설정)
).reset_index()

machine_status_pivot

product machine_id       P_A       P_B       P_C
0           EQP_01  2.794909  2.826909  2.811900
1           EQP_02  2.756000  2.879000  2.742444
2           EQP_03  2.859214  2.842000  2.917833
3           EQP_04  2.724125  2.847800  2.769909

In [60]:
# 제품별 평균 품질 점수와 NG 비율 계산하기

product_report = df_json.groupby("product").agg(
    total_count = ("status", "count"), # 전체 개수 집계
    ng_count = ("status", lambda x:(x=="NG").sum()), # ng에 해당되는 개수 집계
    avg_quality_score = ("quality_score", "mean"),
    avg_temperature = ("temperature", "mean"),
    avg_vibration = ("vibration", "mean")
).reset_index()

product_report

,product,total_count,ng_count,avg_quality_score,avg_temperature,avg_vibration
0,P_A,39,7,91.205128,25.911282,0.331846
1,P_B,39,11,90.687179,26.535128,0.336462
2,P_C,42,8,91.128571,25.723810,0.366548

In [61]:
# NG 비율 계산 컬럼을 추가하기

product_report["ng_ratio"] = product_report["ng_count"] / product_report["total_count"] * 100
product_report = product_report.round(2)

product_report

,product,total_count,ng_count,avg_quality_score,avg_temperature,avg_vibration,ng_ratio
0,P_A,39,7,91.21,25.91,0.33,17.95
1,P_B,39,11,90.69,26.54,0.34,28.21
2,P_C,42,8,91.13,25.72,0.37,19.05

In [62]:
# 리포트 파일을 저장하기

report_path = r"C:\Users\user\Desktop\python_campus\dev\data\result\quality_report.csv"

product_report.to_csv(report_path, index=False, encoding="utf-8-sig")

In [63]:
report_csv = pd.read_csv(report_path, encoding="utf-8-sig")

report_csv

,product,total_count,ng_count,avg_quality_score,avg_temperature,avg_vibration,ng_ratio
0,P_A,39,7,91.21,25.91,0.33,17.95
1,P_B,39,11,90.69,26.54,0.34,28.21
2,P_C,42,8,91.13,25.72,0.37,19.05

speed가 4.5 이하인 데이터를 찾아서 slow_speed_data 변수에 저장하세요.

In [65]:
slow_speed_data = df_json[df_json["speed"]<=4.5]

slow_speed_data.head()

,timestamp,line,machine_id,product,temperature,pressure,speed,humidity,vibration,current,quality_score,status
6,2026-07-01 09:06:00,Line_C,EQP_03,P_C,27.18,3.119,4.32,63.46,0.325,9.17,89.7,OK
9,2026-07-01 09:09:00,Line_C,EQP_03,P_A,22.21,2.749,3.77,56.38,0.459,7.17,86.2,NG
10,2026-07-01 09:10:00,Line_C,EQP_01,P_C,24.88,2.746,4.17,60.52,0.475,8.84,90.4,OK
11,2026-07-01 09:11:00,Line_C,EQP_03,P_B,28.14,3.075,3.57,59.07,0.143,8.67,89.2,NG
17,2026-07-01 09:17:00,Line_B,EQP_03,P_C,26.38,2.722,4.03,57.40,0.525,9.05,87.6,NG

In [67]:
slow_speed_data["speed"].describe()

count    38.000000
mean      4.121579
std       0.286927
min       3.390000
25%       3.895000
50%       4.205000
75%       4.355000
max       4.470000
Name: speed, dtype: float64

vibration이 높은 순서대로 정렬한 뒤 상위 10개 데이터를 확인하세요.

In [70]:
high_vibration = df_json.sort_values(by=["vibration"], ascending=[False])

high_vibration["vibration"].head(10)

95     0.613
102    0.606
109    0.531
107    0.527
17     0.525
47     0.525
49     0.520
78     0.517
7      0.500
19     0.477
Name: vibration, dtype: float64

line별 NG 개수와 NG 비율을 계산하세요.

In [76]:
line_ng_report = df_json.groupby("line").agg(
    totalCount = ("status", "count"),
    ngCount = ("status", lambda x: (x=="NG").sum()),
).reset_index()

line_ng_report["ng_ratio"] = line_ng_report["ngCount"] / line_ng_report["totalCount"] * 100
line_ng_report = line_ng_report.round(2)

line_ng_report

     line  totalCount  ngCount  ng_ratio
0  Line_A          39        4     10.26
1  Line_B          40        9     22.50
2  Line_C          41       13     31.71

machine_id별 평균 센서값과 품질 점수를 계산하고 저장합니다.

In [91]:
machine_avg_report = df_json.groupby("machine_id").agg(
    # avg_sensor = ("current", "mean"), # 평균 센서 값 
    avg_temp = ("temperature", "mean"), # 평균 온도
    avg_press = ("pressure", "mean"), # 평균 압력 
    avg_quality_score = ("quality_score", "mean"), # 품질 점수 

).reset_index()

machine_avg_report = machine_avg_report.round(2)
machine_avg_report

  machine_id  avg_temp  avg_press  avg_quality_score
0     EQP_01     26.62       2.81              90.87
1     EQP_02     25.39       2.80              91.50
2     EQP_03     26.25       2.88              90.44
3     EQP_04     25.75       2.78              91.41

In [92]:
report_path = r"C:\Users\user\Desktop\python_campus\dev\data\result\machine_report.csv"

machine_avg_report.to_csv(report_path, index=False, encoding="utf-8-sig")

In [93]:
df_machine_report = pd.read_csv(report_path, encoding="utf-8-sig")

df_machine_report

  machine_id  avg_temp  avg_press  avg_quality_score
0     EQP_01     26.62       2.81              90.87
1     EQP_02     25.39       2.80              91.50
2     EQP_03     26.25       2.88              90.44
3     EQP_04     25.75       2.78              91.41